#!/bin/bash
jpsxdecPATH="insert path to the jpsxdec jar file here"
realpath "$1" &> /dev/null && file="$(realpath "$1")"
cd "$jpsxdecPATH"

if [ -z ${file+x} ];
then
java -jar jpsxdec.jar
exit
fi

if [ ${file: -4} == ".chd" ]
then
mkdir /tmp/jpsxdec"$$"
tmp="/tmp/jpsxdec"$$"/$(basename "$file".cue)"

#Traps ctrl+C
trap ctrl_c INT

function ctrl_c() {
	rm -r /tmp/jpsxdec"$$"
	exit
}

chdman extractcd -i "$file" -o "$tmp"
java -jar jpsxdec.jar "${tmp%.*}".bin
rm -r /tmp/jpsxdec"$$"
else
java -jar jpsxdec.jar "$file"
fi

